package aeolus.reports;

public enum ReportFeatures {
    TEMPERATURE_CURVE,
    TREND,
    AVERAGES,
    OPERATING_HOURS_HEATING_CURVE,
    OPERATING_HOURS_WATER_CURVE,
    OPERATING_HOURS_TWO_CURVE,
    HIGH_TARIFF_POWER_CURVE,
    LOW_TARIFF_POWER_CURVE,
    HOUSEHOLD_POWER_CURVE,
    HOUSEHOLD_WATER_CURVE
}
